data:
  dataset_list:
    - train-images-idx3-ubyte
    - train-labels-idx1-ubyte
    - t10k-images-idx3-ubyte
    - t10k-labels-idx1-ubyte
  seed: 1
  batch_size: 64

model:
  learning_rate: 1e-3

training:
  epochs: 5
